### ISSUE TITLE
Combining babel and eval leads to a syntax error in eval

### ISSUE THREAD

**Issue by blazzy** [danielgtaylor/nesh#41]
Eval works as expected when I attempt a simple console.log `nesh -e 'console.log("hello world");'` .

But if I introduce the babel flag `nesh -b -e 'console.log("hello world");'`, the eval blows up with the following error:

```
Error in plugin eval:
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at exports.postStart (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/plugins/eval.js:24:19)
    at callPluginMethod (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:73:9)
    at process (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:40:16)
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:52:18
    at callPluginMethod (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:78:14)
    at process (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:40:16)
    at process (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:55:16)
    at processPlugins (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:58:12)
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.0.0/lib/node_modules/nesh/lib/nesh.js:105:14
```

**Comment by deveight** [comment]
I'm having the same issue. Any update on this?

**Comment by jakubholynet** [comment]
Perhaps related to #44 that also fails to combine babel and eval?
